-- PostgreSQL Claims Database Schema
-- This script creates the main claim table according to the requirements

-- Drop table if exists (for development)
DROP TABLE IF EXISTS claim CASCADE;

-- Create the main claim table
CREATE TABLE claim (
    claim_id bigint NOT NULL PRIMARY KEY,
    claim_status_code bigint,
    manual_insured_name varchar(80),
    country_code varchar(3),
    claim_number varchar(20),
    master_claim varchar(1),
    examiner_start_date timestamp,
    examiner_code varchar(10),
    adjusting_office_code varchar(3),
    state_code varchar(2),
    jurisdiction_code bigint,
    file_loc_code bigint,
    file_location_box_number varchar(20),
    incident_type_code bigint,
    address1 varchar(100),
    address2 varchar(100),
    city varchar(50),
    zip_code varchar(10),
    county varchar(50),
    incident_date timestamp,
    fiscal_year_desc varchar(30),
    policy_period_desc varchar(30),
    incident_reported_date timestamp,
    incident_claims_made_date timestamp,
    incident_desc varchar(1000),
    incident_location_desc varchar(500),
    incident_name varchar(80),
    on_insured_premises varchar(1),
    not_covered varchar(1),
    affiliate_claim_number varchar(30),
    org_group_code bigint,
    org1_code varchar(10),
    org2_code varchar(10),
    org3_code varchar(10),
    org4_code varchar(10),
    subrogated varchar(1),
    active varchar(1) DEFAULT '1',
    catastrophe_code varchar(4),
    underwriter_code varchar(10),
    safety varchar(1),
    deductible_amount numeric,
    estimated_subro_recovery numeric,
    estimated_excess_recovery numeric,
    time_tracking varchar(1),
    add_date timestamp,
    add_user varchar(40) DEFAULT 'user',
    edit_date timestamp,
    edit_user varchar(40) DEFAULT 'user',
    excess_reported_date timestamp,
    outside_examiner varchar(100),
    outside_examiner_assigned timestamp,
    asset_number varchar(20),
    funding_source_number varchar(10),
    claim_pay_code bigint,
    claim_pay_code_alternate1 bigint,
    claim_issue_code bigint,
    jurisdiction_claim_number varchar(25),
    not_covered_amount numeric,
    estimated_incident_amount numeric,
    org5_code varchar(10),
    org6_code varchar(10),
    subrogation_statute_date timestamp,
    loss_coverage_code bigint,
    claim_action varchar(255),
    claim_action_code bigint,
    master_claim_number varchar(20),
    examiner_alternate_code bigint,
    escalated varchar(1),
    file_destroyed_date timestamp,
    claim_cause_prdp1_code varchar(10),
    claim_cause_prdp2_code varchar(10),
    claim_cause_prdp3_code varchar(10),
    claim_cause_prdp4_code varchar(10),
    original_source_primary_key bigint,
    original_data_provider_id varchar(9),
    prdp_coverage_code varchar(10),
    prdp_event_code varchar(10),
    rental_agreement_number varchar(20),
    vehicle_asset_number varchar(20),
    customer_number varchar(20),
    renter_identification_number varchar(20),
    siu_flag1 bigint,
    siu_flag2 bigint,
    siu_flag3 bigint,
    siu_flag4 bigint,
    siu_flag5 bigint,
    siu_flag6 bigint,
    siu_flag7 bigint,
    siu_flag8 bigint,
    siu_investigator varchar(40),
    siu_referral_date timestamp,
    siu_start_date timestamp,
    siu_status_code bigint,
    siu_complete_date timestamp,
    siu_referral_status_code bigint,
    reinsurer1_id bigint,
    reinsurer1_claim_number varchar(20),
    reinsurer2_id bigint,
    reinsurer2_claim_number varchar(20),
    file_transfer_date timestamp,
    loss_state varchar(50),
    loss_state_code varchar(5),
    police_dept varchar(100),
    fire_dept varchar(100),
    report_number varchar(20),
    ems_contacted varchar(1),
    total_payout_on_incident numeric,
    total_indemnity_payout_on_incident numeric,
    total_expense_payout_on_incident numeric,
    total_aggregate_to_date numeric,
    occurrence_number varchar(50),
    incident_addr1 varchar(80),
    incident_addr2 varchar(80),
    incident_city varchar(80),
    incident_state varchar(2),
    incident_zip_code varchar(15),
    catastrohpe char(1),
    policy_year_desc varchar(10),
    incident_country_code varchar(3),
    allocation_cost numeric(16, 4),
    converted_claim varchar(1),
    external_claim_number1 varchar(30),
    external_claim_number2 varchar(30),
    external_claim_number3 varchar(30),
    external_claim_number4 varchar(30),
    external_claim_number5 varchar(30),
    denial_rescission_date timestamp,
    acquire_last_indmnty_thru_date timestamp,
    jurisdiction_claim_num_related varchar(25),
    acquisition_status_code char(1),
    new_acquired_claim bigint,
    catastrophe_status_code bigint,
    sticky_notepad_id bigint,
    intake_claim_number varchar(30),
    statistical_type_code varchar(3),
    employee_first_name varchar(100),
    employee_mid_name varchar(100),
    employee_last_name varchar(100),
    ins_same_as_caller varchar(1),
    insurance_company varchar(80),
    employee_address1 varchar(50),
    employee_address2 varchar(50),
    employee_city varchar(100),
    employee_state varchar(2),
    employee_zip varchar(20),
    employee_country varchar(30),
    employee_cell_phone varchar(20),
    employee_home_phone varchar(20),
    employee_work_phone_extn varchar(20),
    employee_fax varchar(20),
    employee_email varchar(50),
    org1_desc varchar(80),
    org2_desc varchar(80),
    org3_desc varchar(80),
    org4_desc varchar(80),
    fraud_statement varchar(100),
    license_number varchar(10),
    employee_work_phone varchar(20),
    claim_closed_date timestamp,
    risk_location_sequence varchar(10),
    claim_cause_code bigint,
    percent_of_liability numeric,
    third_party_insu_company_code varchar(5),
    
    -- Additional fields for the application
    policy_number varchar(50),
    claimant_name varchar(200),
    ssn varchar(11),
    program_code varchar(20),
    insurance_type_id bigint,
    organization_code varchar(20)
);

-- Create indexes for better performance
CREATE INDEX claim_adjusting_office_code_idx ON claim (adjusting_office_code);
CREATE INDEX claim_claim_number_idx ON claim (claim_number);
CREATE INDEX claim_incident_type_code_idx ON claim (incident_type_code);
CREATE INDEX claim_jurisdiction_code_idx ON claim (jurisdiction_code);
CREATE INDEX claim_org1_code_idx ON claim (org1_code);
CREATE INDEX claim_org2_code_idx ON claim (org2_code);
CREATE INDEX claim_state_code_idx ON claim (state_code);
CREATE INDEX claim_active_idx ON claim (active);
CREATE INDEX claim_examiner_code_idx ON claim (examiner_code);
CREATE INDEX claim_status_code_idx ON claim (claim_status_code);
CREATE INDEX claim_add_date_idx ON claim (add_date);
CREATE INDEX claim_incident_date_idx ON claim (incident_date);

-- Add sequence for claim_id (if needed for auto-generation)
-- CREATE SEQUENCE claim_id_seq START WITH 200000000;
-- ALTER TABLE claim ALTER COLUMN claim_id SET DEFAULT nextval('claim_id_seq');

-- Comments for documentation
COMMENT ON TABLE claim IS 'Main claims table containing all claim information';
COMMENT ON COLUMN claim.claim_id IS 'Unique identifier for the claim';
COMMENT ON COLUMN claim.claim_number IS 'Business claim number displayed to users';
COMMENT ON COLUMN claim.claim_status_code IS 'Status of the claim (1=Open, 2=Closed, 3=Pending, 4=Reopened)';
COMMENT ON COLUMN claim.examiner_code IS 'Code identifying the examiner assigned to the claim';
COMMENT ON COLUMN claim.active IS 'Flag indicating if the claim is active (1=Active, 0=Inactive)';